# netlify.toml
[build]
  # Build command (δεν χρειαζόμαστε build για static site)
  command = "echo 'No build required'"
  # Directory to publish
  publish = "."
  # Functions directory (για μελλοντική επέκταση)
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  # SPA fallback - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Headers for PWA and security
[[headers]]
  for = "/*"
  [headers.values]
    # PWA headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Cache headers
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific deploys
[context.production.environment]
  FIREBASE_ENV = "production"

[context.branch-deploy.environment]
  FIREBASE_ENV = "staging"

[context.deploy-preview.environment]
  FIREBASE_ENV = "preview"

# Functions configuration (για μελλοντική χρήση)
[functions]
  # Directory for serverless functions
  directory = "netlify/functions"
  # Node.js version
  node_bundler = "esbuild"

# Form handling (αν χρειαστεί στο μέλλον)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Split testing (A/B testing)
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

# Edge handlers (για προχωρημένη χρήση)
[[edge_handlers]]
  handler = "analytics"
  path = "/api/analytics/*"